site_name: ExplorViz
site_url: https://explorviz.dev
repo_url: https://github.com/explorviz

site_author: 'Alexander Krause-Glau'

docs_dir: 'src'
site_dir: 'docs'

theme:
  logo: explorviz-logo-white.png
  name: material
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
